// flow-typed signature: 8a5264b935e103f2a7c249ae47776e49
// flow-typed version: <<STUB>>/coffeescript_v^2.3.2/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'coffeescript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'coffeescript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'coffeescript/lib/coffeescript/browser' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffeescript/cake' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffeescript/coffeescript' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffeescript/command' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffeescript/grammar' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffeescript/helpers' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffeescript/index' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffeescript/lexer' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffeescript/nodes' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffeescript/optparse' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffeescript/parser' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffeescript/register' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffeescript/repl' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffeescript/rewriter' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffeescript/scope' {
  declare module.exports: any;
}

declare module 'coffeescript/lib/coffeescript/sourcemap' {
  declare module.exports: any;
}

declare module 'coffeescript/register' {
  declare module.exports: any;
}

declare module 'coffeescript/repl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'coffeescript/lib/coffeescript/browser.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffeescript/browser'>;
}
declare module 'coffeescript/lib/coffeescript/cake.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffeescript/cake'>;
}
declare module 'coffeescript/lib/coffeescript/coffeescript.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffeescript/coffeescript'>;
}
declare module 'coffeescript/lib/coffeescript/command.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffeescript/command'>;
}
declare module 'coffeescript/lib/coffeescript/grammar.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffeescript/grammar'>;
}
declare module 'coffeescript/lib/coffeescript/helpers.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffeescript/helpers'>;
}
declare module 'coffeescript/lib/coffeescript/index.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffeescript/index'>;
}
declare module 'coffeescript/lib/coffeescript/lexer.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffeescript/lexer'>;
}
declare module 'coffeescript/lib/coffeescript/nodes.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffeescript/nodes'>;
}
declare module 'coffeescript/lib/coffeescript/optparse.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffeescript/optparse'>;
}
declare module 'coffeescript/lib/coffeescript/parser.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffeescript/parser'>;
}
declare module 'coffeescript/lib/coffeescript/register.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffeescript/register'>;
}
declare module 'coffeescript/lib/coffeescript/repl.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffeescript/repl'>;
}
declare module 'coffeescript/lib/coffeescript/rewriter.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffeescript/rewriter'>;
}
declare module 'coffeescript/lib/coffeescript/scope.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffeescript/scope'>;
}
declare module 'coffeescript/lib/coffeescript/sourcemap.js' {
  declare module.exports: $Exports<'coffeescript/lib/coffeescript/sourcemap'>;
}
declare module 'coffeescript/register.js' {
  declare module.exports: $Exports<'coffeescript/register'>;
}
declare module 'coffeescript/repl.js' {
  declare module.exports: $Exports<'coffeescript/repl'>;
}
