// flow-typed signature: 07087af8de53b977f1d235bce1ae2fe2
// flow-typed version: <<STUB>>/electron-load-devtool_v^1.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-load-devtool'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-load-devtool' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'electron-load-devtool/index' {
  declare module.exports: $Exports<'electron-load-devtool'>;
}
declare module 'electron-load-devtool/index.js' {
  declare module.exports: $Exports<'electron-load-devtool'>;
}
