// flow-typed signature: 67a792a2ac8d2c5abbe4a33173190144
// flow-typed version: <<STUB>>/gulp-install_v^0.6.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-install'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-install' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-install/lib/commandRunner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-install/index' {
  declare module.exports: $Exports<'gulp-install'>;
}
declare module 'gulp-install/index.js' {
  declare module.exports: $Exports<'gulp-install'>;
}
declare module 'gulp-install/lib/commandRunner.js' {
  declare module.exports: $Exports<'gulp-install/lib/commandRunner'>;
}
