// flow-typed signature: d0c6b0f4d04d9adc94a1d97b4e2ba049
// flow-typed version: <<STUB>>/gulp-cjsx_v^3.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-cjsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-cjsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-cjsx/test/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-cjsx/index' {
  declare module.exports: $Exports<'gulp-cjsx'>;
}
declare module 'gulp-cjsx/index.js' {
  declare module.exports: $Exports<'gulp-cjsx'>;
}
declare module 'gulp-cjsx/test/main.js' {
  declare module.exports: $Exports<'gulp-cjsx/test/main'>;
}
