// flow-typed signature: 002dd01021176a66b34f978aea1e5edc
// flow-typed version: <<STUB>>/gulp-jade_v^1.1.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-jade'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-jade' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-jade/index' {
  declare module.exports: $Exports<'gulp-jade'>;
}
declare module 'gulp-jade/index.js' {
  declare module.exports: $Exports<'gulp-jade'>;
}
