// flow-typed signature: 0af6d2d714d5e5e9bb7190796a1472ff
// flow-typed version: <<STUB>>/reduce-reducers_v^0.1.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reduce-reducers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reduce-reducers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reduce-reducers/lib/__tests__/init' {
  declare module.exports: any;
}

declare module 'reduce-reducers/lib/__tests__/reduceReducers-test' {
  declare module.exports: any;
}

declare module 'reduce-reducers/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reduce-reducers/lib/__tests__/init.js' {
  declare module.exports: $Exports<'reduce-reducers/lib/__tests__/init'>;
}
declare module 'reduce-reducers/lib/__tests__/reduceReducers-test.js' {
  declare module.exports: $Exports<'reduce-reducers/lib/__tests__/reduceReducers-test'>;
}
declare module 'reduce-reducers/lib/index.js' {
  declare module.exports: $Exports<'reduce-reducers/lib/index'>;
}
